---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## Importing data

The arguments `skip = 3`, skips the first 3 lines of the data and `n_max = 48` reads at most 48 lines, together avoiding the lines that are metadata not data.

`na = ".."` specifies that missing values are denoted with two periods `..`.

```{r echo=TRUE}
library(readr)
housing <- read_csv("cansim-3270056-eng-1261971602288313454.csv", 
    skip = 3, na = "..", n_max = 48)
```

```{r}
housing 
```


```{r}
housing %>% 
  write_csv("housing_raw.csv")
```

```{r}
housing_reshaped <- housing %>% 
  gather(key = "time", value = "hpi", 
    -Geography, -`New housing price indexes`) %>%
  spread(`New housing price indexes`, hpi) 

housing_reshaped
```


```{r}
housing_clean <- housing_reshaped %>%
  mutate(date = lubridate::parse_date_time(time, order = "my")) 

housing_bc <- housing_clean %>%
  filter(Geography == "Canada" | stringr::str_detect(Geography, "British Columbia")) 

housing_bc %>% 
  select(geography = Geography, date, total = `Total (house and land)`) %>%
  write_csv("housing_bc.csv")

```


```{r}
ggplot(housing_bc, aes(date, `Total (house and land)`)) +
    geom_line(aes(color = Geography))
```